# https://travis-ci.com
language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "chmod +x ./myapp_spring/gradlew && cd myapp_spring && ./gradlew build --info"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - didghwns0514@gmail.com 