# https://travis-ci.com
# https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages

jobs: 
  include: 
    - language: java
      jdk:
        - openjdk8

      branches:
        only:
          - main

      # Travis CI 서버의 Home
      cache:
        directories:
          - '$HOME/.m2/repository'
          - '$HOME/.gradle'

      script: 
        #  /home/travis/build/didghwns0514/awsEC2_React_Spring/node_modules
        #- "chmod +x ./myapp_spring/gradlew && cd myapp_spring && ./gradlew build --info"
        - "chmod +x /home/travis/build/didghwns0514/awsEC2_React_Spring/myapp_spring/gradlew && /home/travis/build/didghwns0514/awsEC2_React_Spring/myapp_spring/gradlew build --info"

    - language: node_js
      node_js:
        - 'stable'
      
      cache:
        directories:
          - '$HOME/.m3/repository'
      
      script:
        #- npm test  # no apt js test yet
        - npm run-script build:env-travis

# https://devconnected.com/how-to-copy-directory-on-linux/
before_deploy:
  - mkdir -p /home/travis/build/didghwns0514/awsEC2_React_Spring/myapp_deploy
  - mkdir -p /home/travis/build/didghwns0514/awsEC2_React_Spring/deploy
  - cp -R /home/travis/build/didghwns0514/awsEC2_React_Spring/myapp_spring/build/libs/*.jar /home/travis/build/didghwns0514/awsEC2_React_Spring/myapp_deploy # jar to deploy
  - cp -R /home/travis/build/didghwns0514/awsEC2_React_Spring/build/* /home/travis/build/didghwns0514/awsEC2_React_Spring/myapp_deploy
  - zip -r /home/travis/build/didghwns0514/awsEC2_React_Spring/myapp_deploy *
  - mv /home/travis/build/didghwns0514/awsEC2_React_Spring/myapp_deploy.zip /home/travis/build/didghwns0514/awsEC2_React_Spring/deploy/myapp_deploy.zip


# deploy할 aws s3
deploy:
  - provider: s3
    local_dir: deploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: myapp-react-spring-bucket # 생성한 S3 버킷
    region: us-east-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: didghwns0514/awsEC2_React_Spring #Github 주소
      branch: main  

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - didghwns0514@gmail.com 